### PR TITLE
Stop view from reloading on orientation change

### PR DESCRIPTION
**Pull request by timmo001**
## Description

The view reloads which causes the webview to reload when the screen orientation changes. This fixes that

### CODE REVIEW

**Comment by marciogranzotto** [comment]
@CedrickFlocon I think this is a good compromise for now. It works and delivers good value to the users. It can be improved in the future.

**Comment by CedrickFlocon** [comment]
This should not be that much complicate ?

**Comment by marciogranzotto** [comment]
For what I understood in the Android Docs, webview's `saveState` no longer saves the display data:

from https://developer.android.com/reference/android/webkit/WebView.html#saveState(android.os.Bundle)
>Please note that this method no longer stores the display data for this WebView. The previous behavior could potentially leak files if restoreState(Bundle) was never called.

also: https://stackoverflow.com/a/2700865/3984316

**Comment by CedrickFlocon** [comment]
Not sure if it's a good idea but we can retain the state with a Fragment

**Comment by koying** [comment]
@CedrickFlocon Just in case, handling config changes through `onConfigurationChanged` still needs this Manifest patch.
Adding "android:configChanges" explicitly says you do that, indeed.

No actually overriding `onConfigurationChanged` in the app means webview is handling it.

**Comment by nicklasl** [comment]
So what is the status of this? I have been waiting for this fix since the launch of the app..

**Comment by balloob** [comment]
Going to close this as this PR has gone stale.

**Pull request closed without merging**
