### PR TITLE
Multiple Notification Options

### PR DESCRIPTION
**Pull request by JBassett**
Fixes: https://github.com/home-assistant/home-assistant-android/issues/354
Fixes: https://github.com/home-assistant/home-assistant-android/issues/353
Fixes: https://github.com/home-assistant/home-assistant-android/issues/349
Fixes: https://github.com/home-assistant/home-assistant-android/issues/335

Needs: https://github.com/home-assistant/mobile-apps-fcm-push/pull/6 to fully function

```
title: 'Title Text'
message: 'Body Text'
data:
  actions:
    - action: test
      title: Click Me
    - action: URI
      title: Open Url
      uri: https://google.com
  image: 'imageUrl'
  tag: tag
  sticky: 'true' # or 'false'
  color: '#2DF56D' # or 'red'
  clickAction: 'https://google.com' # action when clicking main notification
  ttl: 0 # https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidConfig.html#optional-ttl
  priority: 'high' # https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidConfig.html#optional-priority
```

### CODE REVIEW

**Comment by balloob** [comment]
`clickAction`. This can just be a url? That will make it very difficult if we want to expand this in the future to support other actions ? It should either be `{"url": "https://google.com"}` or be called `clickUrl` to make it future proof.

**Comment by JBassett** [comment]
I used clickAction to try to stay in line with the FCM documentation: https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidNotification.html#clickaction  If we want I can change it but I was hoping to stay as close to the existing properties as I can.

**Comment by andriej** [comment]
@JBassett any chance for "icon" as it's in HTML5 using small images?

**Comment by balloob** [comment]
Do not use PRs for feature requests.

**Pull request merged**
