### PR TITLE
Feature/status bar color

### PR DESCRIPTION
**Pull request by JBassett**
Fixes: https://github.com/home-assistant/home-assistant-android/issues/26

### CODE REVIEW

**Comment by dshokouhi** [comment]
Does this grab that color one time or will it update if the theme keeps changing?

**Comment by JBassett** [comment]
It grabs it on app start.  Once the enhancement that was requested to the frontend is complete we should be able to do it when the theme is updated.

**Comment by dshokouhi** [comment]
By app start do you mean initial login or we can force close the app to get it to update?

**Comment by JBassett** [comment]
Force close and reopen will get the latest theme.

**Pull request merged**
