### PR TITLE
Add Fullscreen option

### PR DESCRIPTION
**Pull request by neopilou**
Add an option in the app settings to switch in full screen

2020-01-23_10h19_19

### CODE REVIEW

**Comment by neopilou** [comment]
Sorry for extra commits, but trainings spaces will drive me crazy

**Comment by barrymossel** [comment]
Turning off full screen in setting on Samsung S10 doesn't work. Not even after hard restart of the app.

**Comment by JBassett** [comment]
Not working on Pixel 2 either.  Going to revert for time being.

**Comment by JBassett** [comment]
@neopilou you will need to create a new PR and ensure that the setting actually works,

**Pull request merged**
