### PR TITLE
Android TV Support

### PR DESCRIPTION
**Pull request by neopilou**
Android TV support (NVIDIA Shield or Xiaomi Mi TV Box...)

The navigation control (right, left, up, down for example) cannot be managed in the application, I think it can only be done in the HASS interface (because it is content displayed in a webview) but maybe i'm wrong.

I can suggest other "ic_banner.png":

ic_banner

ic_banner_2

ic_banner-1

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @neopilou, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-android#264).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by robbiet480** [comment]
@neopilou Can you provide a screenshot of it running for the Play Store? We need one to get it published for Android TV. Thanks!

**Comment by neopilou** [comment]
Of course :

Screenshot_20200129-100123
Screenshot_20200129-100145
Screenshot_20200129-100204
Screenshot_20200129-100225
Screenshot_20200129-100251
Screenshot_20200129-100301
Screenshot_20200129-100315
Screenshot_20200129-095822
Screenshot_20200129-100112

**Comment by stbeep1** [comment]
@neopilou Do you have any update on this? Will the HA app support for Android tv officially?

**Pull request merged**
