### PR TITLE
Add kotlin android extensions and use it

### PR DESCRIPTION
**Pull request by marciogranzotto**
Fixes https://github.com/home-assistant/home-assistant-android/issues/40

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @marciogranzotto, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-android#41).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by CedrickFlocon** [comment]
https://github.com/home-assistant/home-assistant-android/pull/4#issuecomment-549031814

**Comment by marciogranzotto** [comment]
@CedrickFlocon I see this more like a good practice, rather than something we should only use if we have a lot of native UI components.

kotlin-android-extensions also has more features that we can use, lie auto-generate Parcelables with an annotation

I think using it makes the project more scalable and easier to maintain.

**Comment by JBassett** [comment]
@CedrickFlocon I agree with @marciogranzotto we are only going to add more native views for settings  (device location, modifying registration, setting up other sensors we want to pass back, multiple urls for HA instance ...)

**Comment by CedrickFlocon** [comment]
each 2 years we have a new way to do a findViewById (Manual, Butterknife, Databiding, and now Kotlin android extensions). I do not agree and I find it useless to add this dependency unless we have more than 50 findViewById in our project.

**Comment by marciogranzotto** [comment]
@CedrickFlocon with that argument, I say that Dagger is useless on this project too, since there's not a need for such a tool to do so little. But that's a design choice and good practice.

kotlin-android-extensions has been around since the beginning of Android Kolin development and has since become the standard for binding views on Kotlin.
I think most contributors that have experience developing Android apps using Kotlin are used to using it and will most likely find it very strange to use `findViewByID`.

**Comment by quthla** [comment]
Or just use https://developer.android.com/jetpack/androidx/releases/fragment?

**Comment by Knoxie** [comment]
Agree with @JBassett and @marciogranzotto. Better to start now with it then have to refactor later on for consistency. Especially with something like this where it's widely used feature.

**Comment by balloob** [comment]
This PR has gone stale and looks like it won't be accepted at this time anyway. Closing it.

**Pull request closed without merging**
